name: Project Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest anybadge
      - name: Test with pytest
        id: tests
        run: cd tests && pytest -vv
        continue-on-error: true
      - name: Generate badge
        if: steps.tests.outcome == 'success'
        run: anybadge --label=pipeline --value=passing --file=pipeline.svg passing=green failing=red
