name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up conda
        uses: s-weigand/setup-conda@v1
      - name: Install dependencies
        run: |
          $CONDA/bin/conda env update -f labelling_env.yml --name base
      - name: Test with pytest
        id: tests
        run: python -m pytest -vv
